name: build

on: workflow_dispatch

jobs:

  build:
    name: build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04', 'macos-10.15', 'windows-latest']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -e .
      - name: Run Pyinstaller
        run: |
          pyinstaller --onefile BeeRef.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: dist/*
          retention-days: 5
